name: Code quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node

      - name: Install dependencies
        run: npm install

      - name: Check package linting
        run: npm run package:lint

      - name: Check code linting
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check
