name: Deploy please

on:
  workflow_dispatch:

jobs:
  deploy-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Scalingo
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PLEASE_TOKEN }}
          REMOTE_URL: ${{ vars.SCALINGO_GIT_URL }}
        run: |
          git remote add scalingo $REMOTE_URL
          git push scalingo HEAD:refs/heads/$(git rev-parse --abbrev-ref HEAD)
