name: Run unit tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: watchthis
          POSTGRES_PASSWORD: watchthis_dev
          POSTGRES_DB: watchthis_user_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node

      - name: Install dependencies
        run: npm install

      - name: Build source code
        run: npm run build

      - name: Set up test database
        run: npm run database:test:setup

      - name: Run unit tests
        run: npm run test
